services:
  - type: web
    name: pdf-to-text-service-1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: {{ TELEGRAM_BOT_TOKEN }}
      - key: GROQ_API_KEY
        value: {{ GROQ_API_KEY }}
    region: oregon
