services:
  - type: web
    name: pdf-to-text-service-1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7858433737:AAGDXo8ws-4hareyWSavBMhjn1e_rkuwbrI
      - key: GROQ_API_KEY
        value: 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
    region: oregon
